// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initApp(connectionInfo ConnectionInfo) (*NatsApp, error) {
	config := NewDefaultConfig()
	db, err := NewDB(connectionInfo)
	if err != nil {
		return nil, err
	}
	userRepo, err := NewUserRepo(config, db)
	if err != nil {
		return nil, err
	}
	httpCleint := NewHttpCleint(config)
	userService := NewUserService(userRepo, httpCleint)
	userHandler := NewUserHandler(userService)
	dashboardRepo, err := NewDashboardRepo(config, db)
	if err != nil {
		return nil, err
	}
	dashboardService := NewDashboardService(dashboardRepo)
	dashboardHandler := NewDashboardHandler(dashboardService)
	natsApp, err := NewNatsApp(userHandler, dashboardHandler)
	if err != nil {
		return nil, err
	}
	return natsApp, nil
}
