// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire/internal"
	"wire/internal/mocks"
)

// Injectors from wire.go:

func initUserHandler(connectionInfo internal.ConnectionInfo, mockHTTP *mock_internal.MockHTTP) (*internal.UserHandler, error) {
	config := internal.NewDefaultConfig()
	db, err := internal.NewDB(connectionInfo)
	if err != nil {
		return nil, err
	}
	userRepo, err := internal.NewUserRepo(config, db)
	if err != nil {
		return nil, err
	}
	userService := internal.NewUserService(userRepo, mockHTTP)
	userHandler := internal.NewUserHandler(userService)
	return userHandler, nil
}
